pipeline {
    agent { 
		docker { 
			image 'alpine:999999999' 
		}
	}
    stages {
        stage('build') {
            steps {
                sh 'cat /etc/alpine-release'
            }
        }
    }
}