pipeline {
    agent { 
		docker { 
			image 'maven:9999999' 
		}
	}
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}